name: ecosteps
description: Um app para construir hábitos sustentáveis.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' 

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  flutter_markdown: ^0.7.1
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/icon.png
    - assets/policies/privacy.md
    - assets/policies/terms.md

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21